#!/bin/sh

case $# in
	0)
		cat $EASTER_CONFIG_FILE
		;;
	1)
		. $EASTER_CONFIG_FILE
		echo "${!1}"
		;;
	2)
		export $1=$2
		export MOAI_ROOT
		envsubst < "$EASTER_ROOT/config-template" > $EASTER_CONFIG_FILE
		;;
esac
