#!/bin/sh

export EASTER=$(readlink -f $0)
export EASTER_ROOT=$(dirname $EASTER)
export EASTER_CONFIG_FILE=~/.easter
export PROJECT_ROOT=`pwd`

if [ -z $1 ]; then
	echo "Usage: easter [command]"
	exit 0
fi

COMMAND_SCRIPT="$EASTER_ROOT/$1"

if [ ! -x $COMMAND_SCRIPT ] || [ ! -f $COMMAND_SCRIPT ]; then
	echo "Unknown command $1"
	exit 1
fi

shift

$COMMAND_SCRIPT $*
