#!/bin/sh

if [ $# -lt 1 ]; then
	echo "Usage: easter run <host-name> [extra args]"
	exit 1
fi

if [ ! -d "hosts/$1" ]; then
	echo "The specified host (hosts/$1) does not exists"
	exit 1
fi

. "$EASTER_ROOT/utils.sh"
read_config "hosts/$1/easter.config"
assert_var HOST_TYPE

export HOST_NAME=$1
export COMMON_BUILD_DIR="$PROJECT_ROOT/build"
export OUT_DIR="$COMMON_BUILD_DIR/bin"
export HOST_BUILD_DIR="$COMMON_BUILD_DIR/$HOST_NAME"
export HOST_DIR="$PROJECT_ROOT/hosts/$HOST_NAME"

case $HOST_TYPE in
	simulator)
		export HOST_TARGET="$COMMON_BUILD_DIR/bin/$HOST_NAME"
		make all -f "$EASTER_ROOT/simulator.make" &&
		$HOST_TARGET $*
		;;
	*)
		echo "Unsupported host type '$HOST_TYPE'"
		exit 1
esac
