#!/bin/sh

. "$EASTER_ROOT/utils.sh"

HOST_DIR=hosts
PLUGIN_DIR=plugins
BUILD_DIR=build

read_project_config
assert_var SIMULATOR

if [ ! -f "build/bin/$SIMULATOR" ]; then #Simulator not built
	assert_file -d "$HOST_DIR/$SIMULATOR"
	. "$EASTER_ROOT/build.sh"
	(build_host "$BUILD_DIR/$SIMULATOR" "$HOST_DIR/$SIMULATOR" $PLUGIN_DIR "build/bin")
	if [ $? -ne 0 ]; then
		echo "Failed to build host"
		exit 1
	fi
fi

build/bin/$SIMULATOR $*
