#!/bin/sh -x

case $# in
	1)
		HOST_NAME=$1
		BUILD_TYPE=develop
		;;
	2)
		HOST_NAME=$2
		BUILD_TYPE=$1
		;;
	*)
		echo "Usage: easter build [build-type] <host-name>"
		echo ""
		echo "Valid build types are: 'debug', 'develop' and 'release'"
		exit 1
esac

if [ ! -d "hosts/$HOST_NAME" ]; then
	echo "The specified host (hosts/$HOST_NAME) does not exists"
	exit 1
fi

. "$EASTER_ROOT/scripts/utils.sh"
read_config "hosts/$HOST_NAME/easter.config"
assert_var host_type

BUILD_SCRIPT=$EASTER_ROOT/scripts/build-$host_type

if [ ! -f "$BUILD_SCRIPT" ]; then
	echo "Unsupported host type '$host_type'"
	exit 1
fi

. "$EASTER_ROOT/scripts/build.sh"
export_build_vars $HOST_NAME $BUILD_TYPE

mkdir -p $OUT_DIR

$BUILD_SCRIPT
