#!/bin/sh

. "$EASTER_ROOT/scripts/utils.sh"

case $# in
	0)
		cat $EASTER_CONFIG_FILE
		;;
	1)
		read_config $EASTER_CONFIG_FILE
		echo "${!1}"
		;;
	2)
		. $EASTER_CONFIG_FILE
		export $1=$2
		export moai_root
		export android_sdk_root
		export android_ndk_root
		envsubst < "$EASTER_ROOT/templates/config-template" > $EASTER_CONFIG_FILE
		;;
esac
