#!/bin/sh

. "$EASTER_ROOT/scripts/utils.sh"

case $# in
	0)
		assert_file -f $EASTER_CONFIG_FILE
		cat $EASTER_CONFIG_FILE
		;;
	1)
		assert_file -f $EASTER_CONFIG_FILE
		read_config $EASTER_CONFIG_FILE
		echo "${!1}"
		;;
	2)
		if [ -f $EASTER_CONFIG_FILE ]; then
			. $EASTER_CONFIG_FILE
		fi
		export $1=$2
		export moai_root
		export android_sdk_root
		export android_ndk_root
		export luajit
		envsubst < "$EASTER_ROOT/templates/config-template" > $EASTER_CONFIG_FILE
		;;
esac
