#!/bin/sh

. "$EASTER_ROOT/scripts/utils.sh"

read_project_config
assert_var project_name

export HOST_TARGET="$COMMON_BUILD_DIR/bin/$project_name-$HOST_NAME-debug.apk"
make all -f "$EASTER_ROOT/make/android.mk"
