#!/bin/sh

. "$EASTER_ROOT/scripts/utils.sh"

read_project_config
read_platform_config "android"
assert_var project_name
assert_var package

HOST_TARGET="$OUT_DIR/$project_name-$HOST_NAME.apk"
adb install -r $HOST_TARGET
adb shell am start -a android.intent.action.MAIN -n $package/$package.MoaiActivity
$EASTER logcat
