#!/bin/sh

. "$EASTER_ROOT/scripts/utils.sh"

read_project_config
read_platform_config "android"
assert_var project_name
assert_var package

HOST_TARGET="$COMMON_BUILD_DIR/bin/$project_name-$HOST_NAME-debug.apk"
adb install -r $HOST_TARGET
adb shell am start -a android.intent.action.MAIN -n $package/$package.MoaiActivity
adb logcat -c
adb logcat MoaiLog:V AndroidRuntime:E *:S
