#!/bin/sh

. "$EASTER_ROOT/scripts/utils.sh"

read_project_config
read_platform_config "android"
assert_var project_name
assert_var package

HOST_TARGET="$OUT_DIR/$project_name-$HOST_NAME.apk"
adb install -r $HOST_TARGET
if [ "$(adb shell dumpsys power | grep mScreenOn | grep -oE '(true|false)')" == false ] ; then #if screen is off
	adb shell input keyevent 26 # wakeup
	adb shell input keyevent 82 # unlock
fi
adb shell am start -a android.intent.action.MAIN -n $package/$package.MoaiActivity
$EASTER logcat
